### ISSUE TITLE
build command should not require repo argument

### ISSUE THREAD

**Issue by farhadi** [erlef/rebar3_hex#299]
We are using `rebar3 hex build` command to build packages for our self-hosted hex repo, but since we have multiple repos defined in rebar.config, `rebar3 hex build` complains that "A repository argument is required", but since build command only builds the package and doesn't publish it to the repo, I think this repo argument can be removed from build command, right?

**Comment by starbelly** [comment]
So, the reason it's required is because someone can define a doc provider on a per repository basis. That said, I think what we can do is check to see if there are 

1. multiple repos
2. If any of them have doc provider config

If 1 and 2 hold true, raise an error instructing the user to provide a repo argument, otherwise, continue.
